from odoo import models
from odoo.tools import float_compare
from odoo.addons.sale_stock.models.sale_order_line import SaleOrderLine as SOLStock


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    def action_send_mrp_request(self):
        self.ensure_one()
        self.order_line._action_launch_stock_rule()


class SaleOrderLine(models.Model):
    _inherit = 'sale.order.line'

    def action_check_production_activity(self):
        self.ensure_one()
        production_id = self.order_id.mrp_production_ids.filtered(lambda mrp: mrp.product_id == self.product_id)
        if production_id:
            return {
                'type': 'ir.actions.client',
                'tag': 'mrp_mo_overview',
                'target': 'new',
                'context': {
                    'model': 'report.mrp.report_mo_overview',
                    'active_id': production_id.id,
                }
            }

def _action_launch_stock_rule(self, previous_product_uom_qty=False):
    """
    Launch procurement group run method with required/custom fields generated by a
    sale order line. procurement group will launch '_run_pull', '_run_buy' or '_run_manufacture'
    depending on the sale order line product rule.
    """
    if self._context.get("skip_procurement"):
        return True
    precision = self.env['decimal.precision'].precision_get('Product Unit of Measure')
    procurements = []
    for line in self:
        line = line.with_company(line.company_id)
        if line.state != 'draft' or line.order_id.locked or line.product_id.type != 'consu':
            continue
        qty = line._get_qty_procurement(previous_product_uom_qty)
        if float_compare(qty, line.product_uom_qty, precision_digits=precision) == 0:
            continue

        group_id = line._get_procurement_group()
        if not group_id:
            group_id = self.env['procurement.group'].create(line._prepare_procurement_group_vals())
            line.order_id.procurement_group_id = group_id
        else:
            # In case the procurement group is already created and the order was
            # cancelled, we need to update certain values of the group.
            updated_vals = {}
            if group_id.partner_id != line.order_id.partner_shipping_id:
                updated_vals.update({'partner_id': line.order_id.partner_shipping_id.id})
            if group_id.move_type != line.order_id.picking_policy:
                updated_vals.update({'move_type': line.order_id.picking_policy})
            if updated_vals:
                group_id.write(updated_vals)

        values = line._prepare_procurement_values(group_id=group_id)
        product_qty = line.product_uom_qty - qty

        line_uom = line.product_uom
        quant_uom = line.product_id.uom_id
        origin = f'{line.order_id.name} - {line.order_id.client_order_ref}' if line.order_id.client_order_ref else line.order_id.name
        product_qty, procurement_uom = line_uom._adjust_uom_quantities(product_qty, quant_uom)
        procurements += line._create_procurements(product_qty, procurement_uom, origin, values)
    if procurements:
        self.env['procurement.group'].run(procurements)

    # This next block is currently needed only because the scheduler trigger is done by picking confirmation rather than stock.move confirmation
    orders = self.mapped('order_id')
    for order in orders:
        pickings_to_confirm = order.picking_ids.filtered(lambda p: p.state not in ['cancel', 'done'])
        if pickings_to_confirm:
            # Trigger the Scheduler for Pickings
            pickings_to_confirm.action_confirm()
    return True

SOLStock._action_launch_stock_rule= _action_launch_stock_rule
